### Chat

POST http://localhost:7071/api/chat

{
    "task": "東京からニューヨークまでの交通費を調べて"
}

### Chat

POST http://localhost:7071/api/chat

{
    "task": "出発地は熊本県で、目的地は東京のMicrosoft品川オフィスで2025/7/1から3泊で出張計画を立ててください"
}

### chat
POST http://localhost:7071/api/chat

{
    "task": "私は正社員です。出発地は熊本で、目的地は東京の品川で3月5日から3泊で出張計画を立ててください"
}